### ISSUE TITLE
Escalates privileges of contributor to admin

### ISSUE THREAD

**Issue by bkeepers** [bkeepers/github-configurer#12]
@claudiopro pointed out [via twitter](https://twitter.com/claudiopro/status/823643376281145346) that this integration inherently escalates anyone with `push` permissions to `admin`, since they can push config settings.

First, this should be clearly stated in the README and integration page.

Eventually, it might be nice to have a feature that only allow changes to the config file to be merged by specific people/teams, or those with admin access (via a combination of protected branches, required statuses, and branch restrictions).

**Comment by claudiopro** [comment]
@bkeepers Since I brought up the issue, I'm contributing a small update to the README. Feel free to reword / integrate. Not sure how would you add to the integration page? Please assist.
