### ISSUE TITLE
How to make it working?

### ISSUE THREAD

**Issue by denysdovhan** [bkeepers/github-configurer#15]
Hi, nice idea!

We, at [LambdaBooks](https://github.com/LambdaBooks), often use the same labels in our repos. I'm trying to use **github-configurer** for making these labels portable from one repo to another.

I set up an integration and [created a `.github/config.yml` file](https://github.com/LambdaBooks/thelittlebookofruby/commit/9ed344d86e7f45ef33f2f851549c0fb8c33e1f39). Unfortunately, this doesn't work and I have no idea why.

I've made [a small test](https://github.com/LambdaBooks/thelittlebookofruby/commit/cb76869458c37a879c3ec21e7b760322a23659dd#diff-51ae5ef21b0bd169a283475e122567d3R11). As you may see, here is a `has_wiki` option set to `false`, but actually repo still has a **Wiki** page.

Maybe I'm missing something? Could anybody help me?

**Comment by denysdovhan** [comment]
**UPD:** Woops, seems like my small test commit has disabled a wiki. Yeah, this works.

Anyway, I don't understand why [here we have a defined `pr` label](https://github.com/LambdaBooks/clojurescript-unraveled/blob/master/.github/config.yml#L18-L21), but it doesn't appear in [list of labels](https://github.com/LambdaBooks/clojurescript-unraveled/labels).

**Comment by bkeepers** [comment]
Hey @denysdovhan, depending on the order of operations, you might have been bitten by #1.

> Anyway, I don't understand why [here we have a defined `pr` label](https://github.com/LambdaBooks/clojurescript-unraveled/blob/master/.github/config.yml#L18-L21), but it doesn't appear in [list of labels](https://github.com/LambdaBooks/clojurescript-unraveled/labels).

I can duplicate this. It looks like I may have mis-configured the GitHub Integration and not asked for enough permissions.

**Comment by bkeepers** [comment]
Confirmed that I messed up when creating the Integration and didn't give it enough permissions. Unfortunately, there's not a way to change permissions on the integration after it's created yet, so I had to create a new instance.

If you install this it should work now: https://github.com/integration/configurer
